controller_joints_names: ['', 'joint01', 'joint02', 'joint03', 'joint04', 'joint05', 'joint06', 'joint07', 'joint08', 'joint09', 'joint10', 
'joint11', 'joint12', 'joint13', 'joint14', 'joint15', 'joint16', 'joint17', 'joint18', 'joint19', 'joint20', 
'joint21', 'joint22', 'joint23', 'joint24', 'joint25', 'joint26', 'joint27', 'joint28', 'joint29', 'joint30',
'joint31', 'joint32', 'joint33', 'joint34', 'joint35', 'joint36', 'joint37', 'joint38', 'joint39', 'joint40',
'joint41', 'joint42', 'joint43', 'joint44', 'joint45', 'joint46', 'joint47', 'joint48', 'joint49', 'joint50', ]

joint_effort_controller:
    type: effort_controller/JointEffortController
    publish_rate: 50  

  # Effort Controllers ---------------------------------------  

joint01_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint02
    pid: {p: 0, i: 0, d: 0}

joint02_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint02
    pid: {p: 0, i: 0, d: 0}
    
joint03_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint03
    pid: {p: 0, i: 0, d: 0}
    
joint04_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint04
    pid: {p: 0, i: 0, d: 0}
    
joint05_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint05
    pid: {p: 0, i: 0, d: 0}
    
joint06_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint06
    pid: {p: 0, i: 0, d: 0}
    
joint07_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint07
    pid: {p: 0, i: 0, d: 0}
    
joint08_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint08
    pid: {p: 0, i: 0, d: 0}

joint09_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint09
    pid: {p: 0, i: 0, d: 0}
    
joint10_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint10
    pid: {p: 0, i: 0, d: 0}
    
joint12_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint12
    pid: {p: 0, i: 0, d: 0}
    
joint13_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint13
    pid: {p: 0, i: 0, d: 0}
    
joint14_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint14
    pid: {p: 0, i: 0, d: 0}
    
joint15_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint15
    pid: {p: 0, i: 0, d: 0}
    
joint16_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint16
    pid: {p: 0, i: 0, d: 0}
    
joint17_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint17
    pid: {p: 0, i: 0, d: 0}
    
joint18_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint18
    pid: {p: 0, i: 0, d: 0}

joint19_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint19
    pid: {p: 0, i: 0, d: 0}
    
joint20_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint20
    pid: {p: 0, i: 0, d: 0}
    
joint22_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint22
    pid: {p: 0, i: 0, d: 0}
    
joint23_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint23
    pid: {p: 0, i: 0, d: 0}
    
joint24_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint24
    pid: {p: 0, i: 0, d: 0}
    
joint25_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint25
    pid: {p: 0, i: 0, d: 0}
    
joint26_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint26
    pid: {p: 0, i: 0, d: 0}
    
joint27_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint27
    pid: {p: 0, i: 0, d: 0}
    
joint28_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint28
    pid: {p: 0, i: 0, d: 0}

joint29_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint29
    pid: {p: 0, i: 0, d: 0}
    
joint30_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint30
    pid: {p: 0, i: 0, d: 0}
    
joint32_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint32
    pid: {p: 0, i: 0, d: 0}
    
joint33_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint33
    pid: {p: 0, i: 0, d: 0}
    
joint34_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint34
    pid: {p: 0, i: 0, d: 0}
    
joint35_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint35
    pid: {p: 0, i: 0, d: 0}
    
joint36_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint36
    pid: {p: 0, i: 0, d: 0}
    
joint37_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint37
    pid: {p: 0, i: 0, d: 0}
    
joint38_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint38
    pid: {p: 0, i: 0, d: 0}

joint39_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint39
    pid: {p: 0, i: 0, d: 0}
    
joint40_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint40
    pid: {p: 0, i: 0, d: 0}
    
joint42_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint42
    pid: {p: 0, i: 0, d: 0}
    
joint43_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint43
    pid: {p: 0, i: 0, d: 0}
    
joint44_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint44
    pid: {p: 0, i: 0, d: 0}
    
joint45_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint45
    pid: {p: 0, i: 0, d: 0}
    
joint46_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint46
    pid: {p: 0, i: 0, d: 0}
    
joint47_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint47
    pid: {p: 0, i: 0, d: 0}
    
joint48_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint48
    pid: {p: 0, i: 0, d: 0}

joint49_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint49
    pid: {p: 0, i: 0, d: 0}
    
joint50_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint50
    pid: {p: 0, i: 0, d: 0}